default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: dmitry
  password: zqpmxwon
  database: BlogDataBase
  host: localhost
  timeout: 5000

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
